name: send tip

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s -X POST -H "Content-Type: application/json" -d "{\"content\": \"$(shuf -n 1 tips.txt)\"}" "$WEBHOOK_URL"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
